## Import Libraries 

In [1]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

## Load Data

In [2]:
train_path= "./Data set/train.csv"
test_path= "./Data set/test.csv"

train_df= pd.read_csv(train_path)
test_df= pd.read_csv(test_path)

print("Shape of training: ", train_df.shape)
print("shape of test: ", test_df.shape)

Shape of training:  (42000, 785)
shape of test:  (28000, 784)


In [3]:
# Split Features from label
features = train_df.iloc[:, 1::1].to_numpy()
labels = train_df.label.to_numpy()

# test data to numpy
test_df = test_df.to_numpy()

print("Shape of features: ",features.shape)
print("features Type: ", type(features))
print("Shape of labels: ",labels.shape)
print("features Type: ", type(labels), "\n")

print(f"test_df :  {test_df.shape} \nType : {type(test_df)} \n")

print("features values : \n", features[0:5, :], "\n")

print("labels values : ", labels[0:5])

Shape of features:  (42000, 784)
features Type:  <class 'numpy.ndarray'>
Shape of labels:  (42000,)
features Type:  <class 'numpy.ndarray'> 

test_df :  (28000, 784) 
Type : <class 'numpy.ndarray'> 

features values : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 

labels values :  [1 0 1 4 0]


In [4]:
# Normalize data 
X= features/255
test= test_df/255
y= labels

print(f"Shape of Normalized Train features data : {X.shape} \nShpae of Normalized Test data : {test_df.shape}")

print(X[0:5, :], "\n")

print(test_df[0:5, :], "\n")

Shape of Normalized Train features data : (42000, 784) 
Shpae of Normalized Test data : (28000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 



In [5]:
# Splitting the Normalized data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=20)

## Model Training
using K-Nearest Neighbours Classifiier, since the normalized data improved the Linear SVC model, I choosen to go ahead to use it on the KNN model as is.

In [6]:
clf_neigh= KNeighborsClassifier(n_neighbors=10, weights="uniform")
clf_neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

## Model Predicton

In [7]:
Pred_neigh= clf_neigh.predict(X_test)
print("KNN model predictions: ",Pred_neigh, "\n")
print(f"Accuracy score non linear :  {accuracy_score(y_test, Pred_neigh)}")

KNN model predictions:  [2 6 4 ... 4 8 6] 

Accuracy score non linear :  0.9607503607503608


In [9]:
predictions= clf_neigh.predict(test)

predictions

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [10]:
submission_knn=pd.DataFrame({"ImageId": list(range(1,len(predictions)+1)),
                         "Label": predictions})

submission_knn.to_csv("submission_knn.csv", index=False, header=True)

submission_knn.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      4
4        5      3